<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>domain</string>
	</array>
	<key>name</key>
	<string>derplanner</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>include</key>
			<string>#translation-unit</string>
		</dict>
	</array>
	<key>repository</key>
	<dict>
		<key>body</key>
		<dict>
			<key>name</key>
			<string>meta.body.derplanner</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#comment</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#literal</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#type</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#case</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#operator</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#call</string>
				</dict>
			</array>
		</dict>
		<key>call</key>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>support.function.derplanner</string>
				</dict>
			</dict>
			<key>match</key>
			<string>([a-zA-Z_\!\?][\w\!\?]*)\s*\(</string>
			<key>name</key>
			<string>meta.funcion-call.derplanner</string>
		</dict>
		<key>case</key>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.control.derplanner</string>
				</dict>
			</dict>
			<key>match</key>
			<string>\b(case|each)\b</string>
			<key>name</key>
			<string>meta.case.derplanner</string>
		</dict>
		<key>comment</key>
		<dict>
			<key>name</key>
			<string>comment.derplanner</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#comment-line</string>
				</dict>
			</array>
		</dict>
		<key>comment-line</key>
		<dict>
			<key>match</key>
			<string>(//).*$\n?</string>
			<key>name</key>
			<string>comment.line.derplanner</string>
		</dict>
		<key>declaration-block</key>
		<dict>
			<key>begin</key>
			<string>\b(fact|prim|extern|const|macro)\b</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>storage.type.derplanner</string>
				</dict>
			</dict>
			<key>end</key>
			<string>\}</string>
			<key>name</key>
			<string>meta.declaration.block.derplanner</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#body</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#declaration-fact</string>
				</dict>
			</array>
		</dict>
		<key>declaration-fact</key>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>entity.name.type.derplanner</string>
				</dict>
			</dict>
			<key>match</key>
			<string>\b([a-zA-Z_!\?][\w!\?]*)\b</string>
			<key>name</key>
			<string>meta.declaration.fact.derplanner</string>
		</dict>
		<key>declaration-single-item</key>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>storage.type.derplanner</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>entity.name.type.derplanner</string>
				</dict>
			</dict>
			<key>match</key>
			<string>\b(domain|fact|prim|extern|task|macro|const)\b\s+([a-zA-Z_!\?][\w!\?]*)</string>
			<key>name</key>
			<string>meta.declaration.derplanner</string>
		</dict>
		<key>literal</key>
		<dict>
			<key>name</key>
			<string>literal.derplanner</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#numeric-literal</string>
				</dict>
			</array>
		</dict>
		<key>logic-operator</key>
		<dict>
			<key>match</key>
			<string>~|\||&amp;|</string>
			<key>name</key>
			<string>keyword.operator.arithmetic.derplanner</string>
		</dict>
		<key>numeric-literal</key>
		<dict>
			<key>match</key>
			<string>\b[0-9]+(\.[0-9]+)?\b</string>
			<key>name</key>
			<string>constant.numeric.derplanner</string>
		</dict>
		<key>operator</key>
		<dict>
			<key>match</key>
			<string>\||&amp;|=|==|~=|&lt;|&lt;=|&gt;|&gt;=|\+|-|\*|/</string>
			<key>name</key>
			<string>keyword.operator.derplanner</string>
		</dict>
		<key>translation-unit</key>
		<dict>
			<key>name</key>
			<string>meta.unit.derplanner</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#body</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#declaration-single-item</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#declaration-block</string>
				</dict>
			</array>
		</dict>
		<key>type</key>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>storage.type.derplanner</string>
				</dict>
			</dict>
			<key>match</key>
			<string>\b(int8|int32|int64|id32|id64|float|vec3)\b</string>
			<key>name</key>
			<string>meta.type.derplanner</string>
		</dict>
	</dict>
	<key>scopeName</key>
	<string>source.derplanner</string>
	<key>uuid</key>
	<string>8510cad0-ba2a-453b-88e2-3f0aaec80d3e</string>
</dict>
</plist>
